# Next Theme Configuration
# Documentation: https://theme-next.js.org/docs/

# Schemes
# scheme: Muse
# scheme: Mist
# scheme: Pisces
# scheme: Gemini
# scheme: Apollon

scheme: Gemini

# Dark Mode
darkmode: false

# Menu
menu:
  home: / || home
  about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  # schedule: 日程 || calendar
  # sitemap: 站点地图 || sitemap
  # commonweal: 公益 || heartbeat

# Sidebar
sidebar:
  # Sidebar Position. 
  # position: left
  # position: right
  position: left

  # Sidebar Display. 
  # display: post
  # display: always
  # display: hide
  display: post

# Avatar
avatar:
  url: /images/touxiang.jpg
  rounded: true
  opacity: 1
  rotated: false

# Author comment
author_comment: true

# Table of Contents in the Sidebar
toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 6

# Social Links
# social:
#   GitHub: https://github.com/yourname || github
#   Twitter: https://twitter.com/yourname || twitter
#   Weibo: https://weibo.com/yourname || weibo
#   Instagram: https://instagram.com/yourname || instagram
#   Linkedin: https://linkedin.com/in/yourname || linkedin

# Footer
footer:
  enable: true
  copyright: © 2025 游走的小夜叉. 保留所有权利.
  # footer.custom_text: 由 <a href="https://pages.github.com/" target="_blank">GitHub Pages</a> 提供支持

# Creative Commons 4.0 International License.
# cc:
#   BY: true
#   NC: true
#   ND: true
#   SA: true

# Back to top button
back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: false
  # Scroll percent label in b2t button.
  scrollpercent: true

# Code Highlight theme
# Available values: normal | night | night eighties | night blue | night bright
highlight_theme: normal

# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Web Analytics
# google_analytics:
#   tracking_id: UA-xxxxxxxxx-x
#   anonymize_ip: true

# utterances
# utterances:
#   repo: your-github-username/your-blog-repo
#   issue_term: pathname
#   label: Comment
#   theme: github-light

# Disqus
# disqus:
#   shortname: your-disqus-shortname
#   apikey: your-disqus-api-key
#   lazyload: false
#   placeholder: Load comments...

# Valine - 支持匿名评论的轻量级评论系统
valine:
  appid: your-leancloud-appid  # 请替换为你的LeanCloud App ID
  appkey: your-leancloud-appkey  # 请替换为你的LeanCloud App Key
  placeholder: 说点什么吧...
  avatar: monsterid  # 评论者头像样式
  meta: [nick]  # 只显示昵称
  pageSize: 10
  lang: zh-CN  # 设置为中文
  visitor: true  # 显示文章阅读量
  highlight: true

# Markdown
# markdown:
#   preset: default
#   render:
#     html: true
#     xhtmlOut: false
#     breaks: true
#     linkify: true
#     typographer: true
#   plugins:
#     - markdown-it-abbr
#     - markdown-it-footnote
#     - markdown-it-ins
#     - markdown-it-sub
#     - markdown-it-sup
#     - markdown-it-emoji

# Search
# Algolia Search
# algolia_search:
#   enable: false
#   hits:
#     per_page: 10
#   labels:
#     input_placeholder: Search for Posts
#     hits_empty: "We didn't find any results for the search: ${query}"
#     hits_stats: "${hits} results found in ${time} ms"

# Local Search
# local_search:
#   enable: true
#   trigger: auto
#   top_n_per_article: 1
#   unescape: false
#   preload: false

# Other
# since: 2023

# Custom CSS
# custom_css:
#   - /css/custom.css

# Custom JS
# custom_js:
#   - /js/custom.js